steps:
- name: 'gcr.io/cloud-builders/git'
  id: set-read-key
  secretEnv: ['READ_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$READ_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh
#Perform the terraform fmt 
- name: 'northamerica-northeast1-docker.pkg.dev/${_REGISTRY_PROJECT}/builders/${_TERRAFORM_VERSION}'
  id: terraform-fmt
  dir: ${_DIR}/${_TF_DIR}
  entrypoint: bash
  args: 
  - '-c' # pass what follows as a command to bash
  - |
    terraform fmt -check ${_TF_RELATIVE_PATH} ; if [ "$?" -ne 0 ]; then echo "Please run terraform fmt to correct code"; exit 42; else exit 0; fi
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
  volumes:
  - name: 'ssh'
    path: /root/.ssh

#Perform the terraform plan 
- name: 'northamerica-northeast1-docker.pkg.dev/${_REGISTRY_PROJECT}/builders/${_TERRAFORM_VERSION}'
  id: terraform-plan
  dir: ${_DIR}/${_TF_DIR}
  entrypoint: bash
  args: 
  - '-c' # pass what follows as a command to bash
  - |
    terraform init -backend-config="${_BACKEND_CONFIG_BUCKET}" -backend-config="${_BACKEND_CONFIG_PREFIX}" ${_TF_RELATIVE_PATH} ; if [ "$?" -ne 0 ]; then exit 43; fi
    terraform validate -no-color ${_TF_RELATIVE_PATH};  if [ "$?" -ne 0 ]; then exit 44; fi
    terraform ${_TF_COMMAND} -var-file=${_VAR_FILE} ${_TF_RELATIVE_PATH};  if [ "$?" -ne 0 ]; then exit 45; fi
  env:
    - "TF_VAR_project-name=${PROJECT_ID}"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
substitutions:
    _KEY_PROJECT: cio-secrets-pr-cb7b98
    _READ_KEY_NAME: rpabot_read_key
    _KEY_VERSION: "latest"
    _REGISTRY_PROJECT: cio-gke-devops-e4993356
    _TERRAFORM_VERSION: terraform:0.13.3
    _DIR: .
    _TF_COMMAND: plan
    _TF_DIR: terraform
    _TF_RELATIVE_PATH: .
    _BACKEND_CONFIG_BUCKET: bucket=tf-state-${PROJECT_ID} 
    _BACKEND_CONFIG_PREFIX: prefix=terraform/np
    _VAR_FILE: np.tfvars
availableSecrets:
  secretManager:
  - versionName: projects/${_KEY_PROJECT}/secrets/${_READ_KEY_NAME}/versions/${_KEY_VERSION}
    env: 'READ_KEY'
timeout: 1200s