channel_portal_database_id  = "cio-channel-portal-pr-6567f7:channel-portal-pr"
channel_portal_project_id   = "cio-channel-portal-pr-6567f7"
cpl_web_container_name      = "channel-portal-web"
cpl_exp_container_name      = "cio-channel-portal-light-exp-api"
channel_portal_project_no   = "167665948143"
channel_portal_enable_alert = "true"